class_names = {
    0: "Giới hạn tốc độ 20 km/h",
    1: "Giới hạn tốc độ 30 km/h",
    2: "Giới hạn tốc độ 50 km/h",
    3: "Giới hạn tốc độ 60 km/h",
    4: "Giới hạn tốc độ 70 km/h",
    5: "Giới hạn tốc độ 80 km/h",
    6: "Hết giới hạn tốc độ 80 km/h",
    7: "Giới hạn tốc độ 100 km/h",
    8: "Giới hạn tốc độ 120 km/h",
    9: "Cấm vượt",
    10: "Cấm xe > 3.5 tấn vượt",
    11: "Quyền ưu tiên tại giao lộ kế tiếp",
    12: "Đường ưu tiên",
    13: "Nhường đường",
    14: "Dừng lại (STOP)",
    15: "Cấm xe",
    16: "Cấm xe > 3.5 tấn",
    17: "Cấm vào",
    18: "Cảnh báo nguy hiểm chung",
    19: "Đường cong nguy hiểm bên trái",
    20: "Đường cong nguy hiểm bên phải",
    21: "Đường cong kép",
    22: "Đường gập ghềnh",
    23: "Đường trơn trượt",
    24: "Đường hẹp bên phải",
    25: "Công trường",
    26: "Đèn tín hiệu giao thông",
    27: "Người đi bộ",
    28: "Trẻ em qua đường",
    29: "Người đi xe đạp",
    30: "Cảnh báo băng tuyết/đá",
    31: "Động vật hoang dã băng qua",
    32: "Hết mọi giới hạn tốc độ và cấm vượt",
    33: "Rẽ phải bắt buộc",
    34: "Rẽ trái bắt buộc",
    35: "Đi thẳng bắt buộc",
    36: "Đi thẳng hoặc rẽ phải",
    37: "Đi thẳng hoặc rẽ trái",
    38: "Đi vòng sang phải",
    39: "Đi vòng sang trái",
    40: "Đi vòng bắt buộc (vòng xuyến)",
    41: "Hết cấm vượt",
    42: "Hết cấm vượt xe > 3.5 tấn"
}
